[package]
name = "protobuf_gen"
version = "0.1.0"
authors = ["Joshua Lockerman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { version = "2.10.2", features = ["with-bytes"] }
protoc-rust = "2.10.2"


